### PR TITLE
Adding GridLayout

### PR DESCRIPTION
**Pull request by GabrielScheibler**
Adding GridLayout supporting master and slave tiles
Adding GridLayout tab to the config ui
Adding a description to the layouts field in the config ui

### CODE REVIEW

**Review by laloch — CHANGES_REQUESTED** [review]
This is awesome @GabrielScheibler! Thanks for putting this in and sorry for the delay.
Could you please add an option (possibly defaulting to `off`) to have a master tile in the Grid layout too?

**Comment by laloch** [comment]
OK, I did, however, already found an issue.
In the below Grid layout configuration I can't move the active tile to the right using <kbd>Meta</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd> shortcut anymore.

Screenshot_20201106_194828

**Comment by v3ss0n** [comment]
This is the layout i am wiring for , @faho  can you take a look?

**Comment by GabrielScheibler** [comment]
@laloch 

> Could you please add an option (possibly defaulting to `off`) to have a master tile in the Grid layout too?

In the grid layout you can control master count with the same shortcuts as in the half layout, and  the master count is set to zero by default. I think that should solve the problem, unless you are talking about the way new columns are added to the grid?


> In the below grid layout configuration I can't move the active tile to the right using Meta+Shift+L shortcut anymore.

I actually cannot reproduce this issue, works just fine for me. Can you narrow down under which circumstances it breaks?
And does it only break on the grid layout?

**Comment by GabrielScheibler** [comment]
> In the below Grid layout configuration I can't move the active tile to the right using Meta+Shift+L shortcut anymore.

@laloch , the last commit should fix the issue you mentioned

**Comment by GabrielScheibler** [comment]
> In the below Grid layout configuration I can't move the active tile to the right using Meta+Shift+L shortcut anymore.

@laloch , the issue you mentioned should be solved with the latest commits

**Comment by laloch** [comment]
> > In the below Grid layout configuration I can't move the active tile to the right using Meta+Shift+L shortcut anymore.
> 
> @laloch , the issue you mentioned should be solved with the latest commits

Yep, I can confirm that it works now, thanks!

**Comment by laloch** [comment]
> > Could you please add an option (possibly defaulting to off) to have a master tile in the Grid layout too?
> 
> In the grid layout you can control master count with the same shortcuts as in the half layout, and the master count is set to zero by default. I think that should solve the problem, unless you are talking about the way new columns are added to the grid?

Yes, I know. I can, however, imagine that users of ultrawide (21:9) and super ultrawide (32:9) monitors would prefer to have always at least one master tile per desktop and it's super annoying to add the master tile manually each time.

**Comment by GabrielScheibler** [comment]
> Yes, I know. I can, however, imagine that users of ultrawide (21:9) and super ultrawide (32:9) monitors would prefer to have always at least one master tile per desktop and it's super annoying to add the master tile manually each time.

Ah okay, I see.
I added the option to specify the default master count in the latest commit.

**Review by laloch — APPROVED** [review]

**Comment by laloch** [comment]
Thanks @GabrielScheibler, this looks great to me! @faho, could you please take a look?

**Comment by faho** [comment]
Nice, merged, thanks!

**Pull request merged**
