### PR TITLE
Layout rotation

### LINKED ISSUE #76: Make direction of blade layout configurable
Currently the blade layout positions windows one next to the other (windows are maximized vertically). There should be an option to position windows one below the other (windows maximized horizontally). This would make the layout much more useful for screens rotated 90°.

### LINKED ISSUE #109: Support vertical layouts
I have two secondary displays, both of which are in vertical (H > W) configurations. kwin-tiling only lets me use horizontal layouts, where the master window is to the left or right of other windows; however, this results in a rather dis-satisfactory layout for vertical displays, as the windows are uselessly narrow and excessively tall.

### LINKED ISSUE #125: Master on the right half in spiral layout (or in half layout)
Hello, 
It would be great to have a mirrored version of the spiral layout (one window is on the right half of the screen and all the others placed on the left according to the selected layout).

Maybe there is a way to achieve this?   (I tried to increase the number of masters but couldn't do it).

### PR DESCRIPTION
**Pull request by laloch**
This is an attempt to implement layout rotation in a generic manner i.e. by coordinate transformations rather than by adjusting each layout.
~~Only 90° rotation works so far, but that makes vertical layout already possible.~~

The default layout rotation chortcut is <kbd>Meta</kbd> + <kbd>Shift</kbd> + <kbd>r</kbd>

closes #76
closes #125 
closes #109

### CODE REVIEW

**Comment by laloch** [comment]
The layout rotation implementation is currently wrong. It works for 90° rotation just coincidentally. The current implementation rotates screen and tile coordinates around origin. Correct implementation would be to first translate the screen center to origin, perform the rotation and then translate it back (i.e. rotate around screen center).

**Comment by laloch** [comment]
@faho: I noticed that you expressed some disfavor of this kind of generic layout transformations in the past discussions. I can close and abandon this PR if you wish...

**Comment by laloch** [comment]
This is now ready to land. We can, however, still abandon it of course.

**Comment by faho** [comment]
This is quite smartly implemented!

One thing that I'd think would improve this quite a bit is to add some way to choose it per-layout, e.g. via the conf-string - like `HalfLayout@270` or something? Or if you don't want to, or want to do it later, we can merge this now.

>I noticed that you expressed some disfavor of this kind of generic layout transformations in the past discussions

To be honest I was simply assuming it'd be much more work.

**Comment by laloch** [comment]
> This is quite smartly implemented!

I'm quite a smart guy, you know... :wink: 

> One thing that I'd think would improve this quite a bit is to add some way to choose it per-layout, e.g. via the conf-string - like HalfLayout@270 or something?

Yes! I like the idea very much.

> Or if you don't want to, or want to do it later, we can merge this now.

Yes, merge this please, I'd like to first finish the activities support and get back to this later.

**Comment by faho** [comment]
>Yes, merge this please,

Fusionado!

**Comment by ilkerhk** [comment]
This is really nice. Thanks!!

**Pull request merged**
