### PR TITLE
Track active screen

### LINKED ISSUE #106: TilingManager._currentScreen is never updated
The title pretty much describes the issue. The field `_currentScreen` is declared inside TilingManager, but I don't see it getting updated anywhere (unlike `_currentDesktop` for which changes are tracked in a signal handler). 

I see no reason to keep this property when we can query `workspace.activeScreen` any time this is needed. And of course, this causes issues with multi-monitor setups (e.g. moveTile does not work on any monitor but the first one).

Since we're at it, even though `_currentDesktop` is correctly handled, I don't see why we shouldn't query `workspace.currentDesktop` directly as well.

### PR DESCRIPTION
**Pull request by laloch**
Fixes #106.

We can now switch layouts on any screen.

### CODE REVIEW

**Comment by faho** [comment]
Out of curiousity: What happens if you close the last client on a screen, or you  move the mouse to a screen without clients? I'm pretty sure this would then give you the wrong screen.

Shouldn't we just check workspace.activeScreen instead?

**Comment by laloch** [comment]
When you close the last client on an active screen and there's still a client on another screen, then the other client get activated and the `_currentScreen` switches. If you close the very last client across all screens, nothing happens.

**Comment by faho** [comment]
>there's still a client on another screen, then the other client get activated and the _currentScreen switches.

Yes. Is that correct? Would you not want things that operate on "the current screen" to operate on the screen the mouse is on?

**Comment by laloch** [comment]
That's a good question. I'm not personally too much into the focus-follows-mouse paradigm, because it often happens to me that I don't really know where my mouse cursor is. Additionally there can be more than one mouse cursor.

**Comment by laloch** [comment]
...in other words, I don't really care about mouse most of the time. I just want to switch layout of the screen I current work at and where my focused window is.

**Comment by faho** [comment]
Okay, so let's just merge this and see if anyone complains.

**Comment by laloch** [comment]
Yes, we can change the behavior anytime.
Thanks for all the reviews!

**Pull request merged**
