### PR TITLE
Add support for activities

### LINKED ISSUE #37: Activity support
right now, tiling assumes that “workspace ID” and “screen ID” correctly identify an area to tile windows in.

but there is a third dimension: activity ID is orthogonal, so windows that are on the same screen and workspace should only be tiled with each other if they are also on the same activity.

### PR DESCRIPTION
**Pull request by laloch**
### TODO
* ~~refactor accesses to `layouts` array~~
* ~~add support for activities~~
* ~~handle clients present on multiple activities~~
* ~~handle moving clients between activities~~

Closes #37

### CODE REVIEW

**Comment by sphinks** [comment]
Very useful merge, waiting for it. @faho do you have plans to merge it?

**Comment by laloch** [comment]
Hi @sphinks, unfortunately this one is still work in progress. I still need to implement the cross-activity window migration.

**Comment by sphinks** [comment]
@laloch I see. Waiting for your fix! As a new window on any desktop affect layout of windows in another activity with the same desktop number. It is very annoying. In case there is a chance to roll-out fix at least for this issue separately - I suppose it will help lot of users even without supporting some functionality. At least, It just keep layout. Thanks!

**Comment by laloch** [comment]
@faho, @sphinks, this is now ready to land.
Currently all activities share the default layout configurations. Unfortunately, I don't now yet, how to fix it.

**Comment by tabroughton** [comment]
hello - sorry for my ignorance but I had just discovered "activities" and got excited about having a work setup and evening set up when I discovered that my current installation of KWinTiling (https://aur.archlinux.org/packages/kwin-scripts-tiling/) has the same desktop id window bug.  A show stopper for me using activities (because I won't live without your excellent tiling scripts now)... so I wondered what is I have to do to get this fix into my desktop?

**Comment by laloch** [comment]
Hi @tabroughton, if you are using the package from AUR, you should already have (basic) support for activities. I'm afraid, I don't understand what "the same desktop id window bug" means. Can you explain please?

**Comment by tabroughton** [comment]
> Can you explain please?

Yes I was referring to the previous comment made by @sphinks 

> As a new window on any desktop affect layout of windows in another activity with the same desktop number. 

Basically the if I launch a program in virtual desktop 1 and then switch activities and launch a new program in desktop 1 (in fresh activity) then the window/tiling size is half the screen, switching to first activity I see desktop 1 has changed window size to the other half of the screen.  I assumed this is what @sphinks was referring to as well.

As for building from the AUR - I see in the pkgbuild script is using this `pkgver=2.3` release and that [2.3 was released last September ](https://github.com/kwin-scripts/kwin-tiling/releases/tag/v2.3)but these commits here weren't merged until November.

Is the fix for the bugs I'm experiencing in this merge? and if so, how can I install it into my desktop please?  (is there a 2.4 release coming up and with the AUR be updated or am I missing something which is quite likely).

**Comment by laloch** [comment]
> As for building from the AUR - I see in the pkgbuild script is using this `pkgver=2.3` release and that [2.3 was released last September ](https://github.com/kwin-scripts/kwin-tiling/releases/tag/v2.3)but these commits here weren't merged until November.

Damn it! You are right!

> Is the fix for the bugs I'm experiencing in this merge? and if so, how can I install it into my desktop please?

Yes, it was merged in on November 26th. You can uninstall the AUR package for now and follow the [Installation](https://github.com/kwin-scripts/kwin-tiling#installation) section of README.
And yes, we should have a release. Sorry for the inconvenience.

**Pull request merged**
